RTS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib import admin
from account.views import base


urlpatterns = [
    path('', base, name="home"),
    path('admin/', admin.site.urls),
    path('account/', include("account.urls")),
    path('cv/', include("cv.urls")),
    path('jobs/', include("jobs.urls")),
    path('careeradvice/', include("careeradvice.urls")),
    path('training/', include("training.urls")),
    path('api/', include("generics.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path, reverse_lazy
from account import views
from django.contrib.auth import views as auth_views


# Create a name space for the account application
app_name = "account"

# Account's URLs
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/',
         auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html',
                                               success_url=reverse_lazy('account:password_change_done')),
         name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html',
                                              success_url=reverse_lazy('account:password_reset_done')),
         name='registration/password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('account:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path('company_register/', views.company_register, name='company_register'),
    path('employee_register/', views.employee_register, name='employee_register'),
    path('profile/', views.profile, name="profile"),
    path('profile/<user_id>/', views.show_profile, name="show_profile"),
    path('edit/', views.profile_edit, name="profile_edit"),
    path('delete_apply/<int:apply_id>/', views.delete_apply, name='delete_apply'),
]

careeradvice/urls.py
from django.urls import path
from . import views
app_name = "careeradvice"

urlpatterns = [
    path('', views.advices, name="advice_list"),
    path('search_advices/', views.search_advices, name="search_advices"),
    path('add_advice/', views.add_advice, name="add_advice"),
    path('details/<int:advice_id>/', views.advice_details, name="advice_details"),
    path('edit/<int:advice_id>/', views.edit_advice, name='advice_edit'),
    path('delete_advice/<int:advice_id>/', views.delete_advice, name="advice_delete")
]

cv/urls.py
from django.urls import path
from . import views
from generics.views import preview

# Namespace for CV app.
app_name = "cv"

# CV urls.
urlpatterns = [
    # Home's urls
    path('', views.have_cv, name="home"),
    # CV's urls.
    path('cv_show/', views.show, name='cv_show'),
    path('cv_make/', views.create, name='create'),
    path('delete/', views.delete, name='delete_cv'),
    path('edit/', views.edit, name='edit'),
    path('preview/<cv_id>/', preview, name='preview'),
]

jobs/urls.py
from django.urls import path
from . import views
app_name = "jobs"
urlpatterns = [
    path('', views.posts, name='post_list'),
    path('add_job/', views.add_job, name='add_job'),
    path('search_job/', views.search_job, name='search_job'),
    path('<job_id>/', views.job_details, name="job_details"),
    path('edit/<int:job_id>/', views.edit_job, name='job_edit'),
    path('add_apply/<job_id>/', views.add_apply, name='add_apply'),
    path('delete/<int:job_id>/', views.delete_job, name="job_delete"),
    path('show_applies/<job_id>/', views.show_applies, name='show_applies'),
    path('apply_details/<int:apply_id>/', views.apply_details, name='apply_details')

]

training/urls.py
from django.urls import path
from . import views


# Create a name space for the training application
app_name = "training"

# Training's urls
urlpatterns = [
    path('', views.trainings_list, name='trainings_list'),
    path('<int:training_id>/', views.training_details, name='training_details'),
    path('add/', views.add_training, name='add_training'),
    path('edit/<training_id>/', views.training_edit, name='edit_training'),
    path('delete/<training_id>/', views.training_delete, name='training_delete'),
    path('payment/', views.payment, name='payment'),
    path('complete/', views.payment_complete, name='complete'),
    path('search_result/', views.search_training, name='search_training')
]

templates/home/footer.html
<style type="text/css">
    .footer-basic {
        background: linear-gradient(135deg, #172a74, #21a9af);
        background-color: #184e8e;
    }

    .footer-basic ul {
        padding: 0;
        list-style: none;
        text-align: center;
        font-size: 18px;
        line-height: 1.6;
        margin-bottom: 0;
    }

    .footer-basic .social > a {
        font-size: 24px;
        line-height: 40px;
        display: inline-block;
        text-align: center;
        border-radius: 50%;
        border: 1px solid #ccc;
        color: inherit;
        opacity: 0.75;
    }

    .footer-basic .copyright {
        margin-top: 2px;
        text-align: center;
        font-size: 13px;
        color: #fff;
        margin-bottom: 0;
    }
</style>
<body>
{% block content %}
{% endblock content %}
</body>
<footer>
    <div class="footer-basic fixed-bottom">
        <footer>
            <p class="copyright">RTS © 2022</p>
        </footer>
    </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

templates/home/header.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700">
    <link rel="stylesheet" href="assets/css/style.css">
    <style type="text/css">
        .header-blue {
            background: linear-gradient(135deg, #172a74, #21a9af);
            background-color: #184e8e;
            padding-bottom: 1px;
            font-family: 'Source Sans Pro', sans-serif;
        }


        .header-blue .navbar {
            background: transparent;
            color: #fff;
            border-radius: 0;
            box-shadow: none;
            border: none;
        }


        .header-blue .navbar .navbar-brand {
            font-weight: bold;
            color: inherit;
        }

        .header-blue .navbar .navbar-brand:hover {
            color: #f0f0f0;
        }

        .header-blue .navbar .navbar-collapse {
            border-top: 1px solid rgba(255, 255, 255, 0.3);
            margin-top: .5rem;
        }

        @media (min-width: 768px) {
            .header-blue .navbar .navbar-collapse {
                border-color: transparent;
                margin: 0;
            }
        }

        .header-blue .navbar .navbar-collapse span .login {
            color: #d9d9d9;
            margin-right: .5rem;
            text-decoration: none;
        }

        .header-blue .navbar .navbar-collapse span .login:hover {
            color: #fff;
        }

        .header-blue .navbar .navbar-toggler {
            border-color: rgba(255, 255, 255, 0.3);
        }

        .header-blue .navbar .navbar-toggler:hover, .header-blue .navbar-toggler:focus {
            background: none;
        }

        .header-blue .navbar .navbar-nav a.active, .header-blue .navbar .navbar-nav > .show .dropdown-item {
            background: none;
            box-shadow: none;
        }

        @media (min-width: 768px) {
            .header-blue .navbar-nav .nav-link {
                padding-left: .7rem;
                padding-right: .7rem;
            }
        }

        @media (min-width: 992px) {
            .header-blue .navbar-nav .nav-link {
                padding-left: 1.2rem;
                padding-right: 1.2rem;
            }
        }

        .header-blue .navbar .navbar-nav > li > .dropdown-menu {
            margin-top: -5px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, .1);
            background-color: #fff;
            border-radius: 2px;
        }

        .header-blue .navbar .dropdown-menu .dropdown-item:focus, .header-blue .navbar .dropdown-menu .dropdown-item {
            line-height: 2;
            color: #37434d;
        }

        .header-blue .navbar .dropdown-menu .dropdown-item:focus, .header-blue .navbar .dropdown-menu .dropdown-item:hover {
            background: #ebeff1;
        }

        .header-blue .action-button, .header-blue .action-button:not(.disabled):active {
            border: 1px solid rgba(255, 255, 255, 0.7);
            border-radius: 40px;
            color: #ebeff1;
            box-shadow: none;
            text-shadow: none;
            padding: .3rem .8rem;
            background: transparent;
            transition: background-color 0.25s;
            outline: none;
        }

        .header-blue .action-button:hover {
            color: #fff;
        }

        .header-blue .navbar .form-inline label {
            color: #d9d9d9;
        }

        .header-blue .navbar .form-inline .search-field {
            display: inline-block;
            width: 80%;
            background: none;
            border: none;
            border-bottom: 1px solid transparent;
            border-radius: 0;
            color: #ccc;
            box-shadow: none;
            color: inherit;
            transition: border-bottom-color 0.3s;
        }

        .header-blue .navbar .form-inline .search-field:focus {
            border-bottom: 1px solid #ccc;
        }

        .header-blue .hero {
            margin-top: 20px;
            text-align: center;
        }

        @media (min-width: 768px) {
            .header-blue .hero {
                margin-top: 60px;
                text-align: left;
            }
        }

        .header-blue .hero h1 {
            color: #fff;
            font-size: 40px;
            margin-top: 0;
            margin-bottom: 15px;
            font-weight: 300;
            line-height: 1.4;
        }

        @media (min-width: 992px) {
            .header-blue .hero h1 {
                margin-top: 190px;
                margin-bottom: 24px;
                line-height: 1.2;
            }
        }

        .header-blue .hero p {
            color: rgba(255, 255, 255, 0.8);
            font-size: 20px;
            margin-bottom: 30px;
            font-weight: 300;
        }

        .header-blue .phone-holder {
            text-align: right;
        }

        .header-blue div.iphone-mockup {
            position: relative;
            max-width: 300px;
            margin: 20px;
            display: inline-block;
        }

        .header-blue .iphone-mockup img.device {
            width: 100%;
            height: auto;
        }

        .header-blue .iphone-mockup .screen {
            position: absolute;
            width: 88%;
            height: 77%;
            top: 12%;
            border-radius: 2px;
            left: 6%;
            border: 1px solid #444;
            background-color: #aaa;
            overflow: hidden;
            background-size: cover;
            background-position: center;
        }

        .header-blue .iphone-mockup .screen:before {
            content: '';
            background-color: #fff;
            position: absolute;
            width: 70%;
            height: 140%;
            top: -12%;
            right: -60%;
            transform: rotate(-19deg);
            opacity: 0.2;
        }

        .profile {
            position: relative;
            left: 750px;
            top: 2px;
        }

        .login {
            position: relative;
            left: 370px;
            top: 2px;
        }

    </style>
</head>

<body>
<div>
    <div class="header-blue fixed-top">
        <nav class="navbar navbar-dark navbar-expand-md navigation-clean-search">
            <div class="container"><a class="navbar-brand" href="{% url 'home' %}">RTS</a>
                {% if request.user.is_authenticated %}
                    <div class="collapse navbar-collapse"
                         id="navcol-1">
                        <ul class="nav navbar-nav">
                            <li class="nav-item" role="presentation">
                                <a class="nav-link active" href="{% url 'careeradvice:advice_list' %}">
                                    Career Advice</a>
                            </li>
                            <li class="nav-item" role="presentation"><a class="nav-link active"
                                                                        href="{% url 'jobs:post_list' %}">Jobs</a></li>
                            <li class="nav-item" role="presentation"><a class="nav-link active"
                                                                        href="{% url 'training:trainings_list' %}">Training</a>
                            </li>
                            <div class="nav-item dropdown profile">
                                <a href="{{ pic }}" class=" pt-1 px-0" role="button" data-toggle="dropdown"
                                   aria-haspopup="true"
                                   aria-expanded="false">
                                    <img class="rounded-circle account-img pic" src="{{ request.user.photo.url }}"
                                         width="25px"
                                         height="25px"
                                         style="border-radius: 50%">
                                    <span class="mb-0 font-small font-weight-bold" style="color: white">
                                {{ request.user.username }}
                                </span>
                                </a>
                                <div class="dropdown-menu dashboard-dropdown dropdown-menu-right mt-2">
                                    <a class="dropdown-item font-weight-bold" href="{% url 'account:profile' %}"><span
                                            class="fas fa-sign-out-alt text-danger"></span>Profile</a>
                                    <div role="separator" class="dropdown-divider"></div>
                                    {% if request.user.is_employee %}
                                        <a class="dropdown-item font-weight-bold" href="{% url 'cv:home' %}">
                                            <span class="fas fa-sign-out-alt text-danger"></span>Your CV</a>

                                        <div role="separator" class="dropdown-divider"></div>
                                    {% endif %}
                                    <a class="dropdown-item font-weight-bold" href="{% url 'account:logout' %}">
                                        <span class="fas fa-sign-out-alt text-danger"></span>Logout</a>
                                </div>
                            </div>
                        </ul>
                    </div>
                {% else %}
                    <button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span
                            class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse"
                         id="navcol-1">
                        <ul class="nav navbar-nav">
                            <li class="nav-item" role="presentation"><a class="nav-link active"
                                                                        href="{% url 'careeradvice:advice_list' %}">Career
                                Advice</a></li>
                            <li class="nav-item" role="presentation"><a class="nav-link active"
                                                                        href="{% url 'jobs:post_list' %}">Jobs</a></li>
                            <li class="nav-item" role="presentation"><a class="nav-link active"
                                                                        href="{% url 'training:trainings_list' %}">Training</a>
                            </li>
                        </ul>
                        <span class="navbar-text login"> <a href="{% url 'account:login' %}" class="login">Log In</a></span><a
                            class="btn btn-light action-button profile" role="button"
                            href="{% url 'account:register' %}">Register</a></div>
                {% endif %}
            </div>
        </nav>
    </div>
</div>
</body>

</html>

templates/home/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        body {
            background-color: #b4d3e5;
        }
    </style>
</head>
<body>

</body>
</html>