RTS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib import admin
from account.views import base


urlpatterns = [
    path('', base, name="home"),
    path('admin/', admin.site.urls),
    path('account/', include("account.urls")),
    path('cv/', include("cv.urls")),
    path('jobs/', include("jobs.urls")),
    path('careeradvice/', include("careeradvice.urls")),
    path('training/', include("training.urls")),
    path('api/', include("generics.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cv/urls.py
from django.urls import path
from . import views
from generics.views import preview

# Namespace for CV app.
app_name = "cv"

# CV urls.
urlpatterns = [
    # Home's urls
    path('', views.have_cv, name="home"),
    # CV's urls.
    path('cv_show/', views.show, name='cv_show'),
    path('cv_make/', views.create, name='create'),
    path('delete/', views.delete, name='delete_cv'),
    path('edit/', views.edit, name='edit'),
    path('preview/<cv_id>/', preview, name='preview'),
]

training/urls.py
from django.urls import path
from . import views


# Create a name space for the training application
app_name = "training"

# Training's urls
urlpatterns = [
    path('', views.trainings_list, name='trainings_list'),
    path('<int:training_id>/', views.training_details, name='training_details'),
    path('add/', views.add_training, name='add_training'),
    path('edit/<training_id>/', views.training_edit, name='edit_training'),
    path('delete/<training_id>/', views.training_delete, name='training_delete'),
    path('payment/', views.payment, name='payment'),
    path('complete/', views.payment_complete, name='complete'),
    path('search_result/', views.search_training, name='search_training')
]

training/models.py
from django.db import models
from django.conf import settings
from phonenumber_field.modelfields import PhoneNumberField
from taggit.managers import TaggableManager
from django.urls import reverse
from generics.models import Category, Countries


class Training(models.Model):
    # A foreign key to the user when the user is deleted the corresponding threads are deleted as well.
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="training_created", on_delete=models.CASCADE)
    # The review's title.
    title = models.CharField(max_length=256)
    # A field to make SEO friendly links.
    slug = models.SlugField(max_length=256)
    # An opening describes what this thread is about.
    description = models.TextField(blank=True)
    # Decimal field holds the price.
    price = models.DecimalField(decimal_places=2, max_digits=10)
    country = models.ForeignKey(Countries, on_delete=models.CASCADE, blank=False)
    # Is this still available or not.
    is_available = models.BooleanField(default=True)
    # The time and date the review was posted, and it's added automatically.
    created = models.DateTimeField(auto_now_add=True)
    # Tags to mark the post.
    tags = TaggableManager()
    # Post's category.
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=False)
    # Post's Update time.
    updated = models.DateTimeField(auto_now=True)
    email = models.EmailField()
    phone_number = PhoneNumberField(unique=True, null=True, blank=True)

    def get_absolute_url(self):
        """Returns a Training object URL."""
        # Build and return a unique and SEO friendly URL for a Training object.
        return reverse('training:training_details', args=[self.id])

    def get_absolute_edit_url(self):
        """Returns a Training object URL to edit."""
        # Build and return a unique for a Training object.
        return reverse('training:edit_training', args=[self.id])

    def get_absolute_delete_url(self):
        """Returns a Training object URL to edit."""
        # Build and return a unique for a Training object.
        return reverse('training:training_delete', args=[self.id])

    def __str__(self):
        return self.title

training/forms.py
from django import forms
from .models import Training


class TrainingForm(forms.ModelForm):
    price = forms.DecimalField(label="Price")

    class Meta:
        model = Training
        fields = ("title", "email", "country", "description", "price", "category", "tags", "phone_number")
        help_texts = {"tags": None}

training/views.py
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from account.models import Profile
from generics.models import Category, Countries
from .models import Training
from .forms import TrainingForm
from django.utils.text import slugify


def trainings_list(request):
    """Lists all the training."""
    # Query all trainings
    trainings = Training.objects.all()
    categories = Category.objects.all()
    countries = Countries.objects.all()
    # A dictionary to send trainings to the HTML
    context = {"trainings": trainings, 'categories': categories, 'countries': countries}
    # Render the trades_list html page
    return render(request, 'trainings_list.html', context)


def add_training(request):
    # Is it a post request ?
    if request.method == 'POST' and request.user.is_trainer:
        # Instantiate a Create Training with the submitted data
        training_form = TrainingForm(request.POST, files=request.FILES)
        # The data are valid ?
        if training_form.is_valid():
            # Create a new training object but don't save it to the database just yet
            new_training_form = training_form.save(commit=False)
            # request username to put it in training
            new_training_form.author = request.user
            # create friendly links
            new_training_form.slug = slugify(new_training_form.title)
            # save training
            new_training_form.save()
            # save tags
            training_form.save_m2m()
            # to go to training page
            return redirect('training:trainings_list')
    else:
        # create empty training
        training_form = TrainingForm()
    context = {'training_form': training_form}
    # to represent add training page
    return render(request, 'add_training.html', context)


def training_details(request, training_id):
    """Retrieves a Training object by id and slug """
    # Try to get a Training object with the passed id and slug
    training_to_display = get_object_or_404(Training, pk=training_id)
    context = {"training_to_display": training_to_display}
    # Render the details of the Training object
    return render(request, 'training_details.html', context)


def training_edit(request, training_id):
    # To search for a specific edit training by id
    training_to_edit = get_object_or_404(Training, id=training_id)
    # To check that the publisher himself
    if request.user != training_to_edit.author:
        return HttpResponse("No Permissions!")
    # Is it a post request ?
    if request.method == "POST" and request.user == training_to_edit.author:
        training_form = TrainingForm(instance=training_to_edit, data=request.POST, files=request.FILES)
        # The data are valid ?
        if training_form.is_valid():
            training_form.save(commit=False)
            # save training
            training_form.save()
            return redirect('training:trainings_list')
    else:
        training_form = TrainingForm(instance=training_to_edit)

    return render(request, "training_edit.html", {"form": training_form})


def training_delete(request, training_id):
    # to get the training id
    training = get_object_or_404(Training, id=training_id)
    # check if the one requesting is the training owner
    if request.user != training.author:
        return HttpResponse("No Permissions!")
    # Is it a post request ? and checks if its by the owner himself
    if request.method == "POST" and request.user == training.author:
        # if so delete the training
        training.delete()
        return redirect('training:trainings_list')
    return render(request, "training_delete.html")


def search_training(request):
    results = []
    categories = Category.objects.all()
    countries = Countries.objects.all()
    sal_category = Category()
    sal_country = Countries()
    query = None
    if request.method == "GET":
        query = request.GET.get('search')
        category = request.GET.get("category_id")
        country = request.GET.get("country_id")

        if category:
            sal_category = Category.objects.filter(pk=category)

        if country:
            sal_country = Countries.objects.filter(pk=country)

        if query != '':
            if Training.objects.filter(Q(tags__name__icontains=query)):
                results = Training.objects.filter(Q(tags__name=query))
            else:
                results = Training.objects.filter(Q(title__icontains=query) |
                                                  Q(description__icontains=query))

        elif query == '':
            results = Training.objects.all()

        if category != "0":
            results = results.filter(Q(category__name=sal_category[0].name))

        if country != "0":
            results = results.filter(Q(country__country=sal_country[0].country))

    return render(request, 'trainings_list.html', {"trainings": results, 'categories': categories, 'countries': countries})


def payment(request):
    return render(request, "paypal.html")


def payment_complete(request):
    profile = Profile.objects.get(pk=request.user.id)
    profile.is_trainer = True
    profile.save()
    return render(request, "complete.html")

training/templates/add_training.html
{% extends 'base.html' %}
{% block content %}
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Add Training</title>
        <style>
            .form-style-5 {
                max-width: 500px;
                padding: 10px 20px;
                background: #f4f7f8;
                margin: 10px auto;
                padding: 20px;
                background: #f4f7f8;
                border-radius: 8px;
                font-family: Georgia, "Times New Roman", Times, serif;
            }

            .form-style-5 fieldset {
                border: none;
            }

            .form-style-5 legend {
                font-size: 1.4em;
                margin-bottom: 10px;
            }

            .form-style-5 label {
                display: block;
                margin-bottom: 8px;
            }

            .form-style-5 input[type="text"],
            .form-style-5 input[type="date"],
            .form-style-5 input[type="datetime"],
            .form-style-5 input[type="email"],
            .form-style-5 input[type="number"],
            .form-style-5 input[type="search"],
            .form-style-5 input[type="time"],
            .form-style-5 input[type="url"],
            .form-style-5 input[type="tel"],
            .form-style-5 textarea,
            .form-style-5 select {
                font-family: Georgia, "Times New Roman", Times, serif;
                background: rgba(255, 255, 255, .1);
                border: none;
                border-radius: 4px;
                font-size: 15px;
                margin: 0;
                outline: 0;
                padding: 10px;
                width: 100%;
                box-sizing: border-box;
                -webkit-box-sizing: border-box;
                -moz-box-sizing: border-box;
                background-color: #e8eeef;
                color: #8a97a0;
                -webkit-box-shadow: 0 1px 0 rgba(0, 0, 0, 0.03) inset;
                box-shadow: 0 1px 0 rgba(0, 0, 0, 0.03) inset;
                margin-bottom: 30px;
            }

            .form-style-5 input[type="text"]:focus,
            .form-style-5 input[type="date"]:focus,
            .form-style-5 input[type="datetime"]:focus,
            .form-style-5 input[type="email"]:focus,
            .form-style-5 input[type="phone_number"]:focus,
            .form-style-5 input[type="search"]:focus,
            .form-style-5 input[type="time"]:focus,
            .form-style-5 input[type="url"]:focus,
            .form-style-5 input[type="tel"]:focus,
            .form-style-5 textarea:focus,
            .form-style-5 select:focus {
                background: #d2d9dd;
            }

            .form-style-5 select {
                -webkit-appearance: menulist-button;
                height: 35px;
            }

            .form-style-5 .number {
                background: #1abc9c;
                color: #fff;
                height: 30px;
                width: 30px;
                display: inline-block;
                font-size: 0.8em;
                margin-right: 4px;
                line-height: 30px;
                text-align: center;
                text-shadow: 0 1px 0 rgba(255, 255, 255, 0.2);
                border-radius: 15px 15px 15px 0px;
            }

            .form-style-5 input[type="submit"],
            .form-style-5 input[type="button"] {
                position: relative;
                display: block;
                padding: 19px 39px 18px 39px;
                color: #FFF;
                margin: 0 auto;
                background: #1a3dbc;
                font-size: 18px;
                text-align: center;
                font-style: normal;
                width: 100%;
                border: 1px solid #1628a0;
                margin-bottom: 10px;
            }

            .form-style-5 input[type="submit"]:hover,
            .form-style-5 input[type="button"]:hover {
                background: #103091;
            }
        </style>
    </head>
    <body>
    <br><br><br>
    <form method="post" class="form-style-5">
        {{ training_form.as_p }}
        <input type="submit" value="Apply"/>
        {% csrf_token %}
    </form>
    </body>
    </html>
{% endblock content %}

training/templates/complete.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Completed</title>
</head>
<body>
<br>
    <br>
    <br>

<center>
<p style="color: green"><b>Congratulations! Payment Successful.</b></p>
</center>
</body>
</html>
{% endblock content %}

training/templates/paypal.html
{% extends 'base.html' %}
{% block content %}
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <!-- Add meta tags for mobile and IE -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <title> PayPal Checkout </title>
    </head>

    <body>
    <br>
    <br>
    <br>
        <div class="flex-row flex-wrap align-items-start ">
            <div class="card profile-card card-header text-white m-2 shadow-lg">
                <h2>
                    <center>Become a Trainer</center>
                </h2>
                <div class="card-body">
                    <center>
                        <p><h6>You Will be able to use training page and download cv templates </h6></p>
                        <p>what are you waiting? Buy it Now!</p>
                        <p>for only 10$</p>
                        <div id="paypal-button-container"></div>
                    </center>
                </div>
            </div>
        </div>

    <script src="https://www.paypal.com/sdk/js?client-id=AQbXKgJDo3IwbjEs_nhC_7_KvKBolRoPqpsD6UxolgfFNo5xXJv9j96WtRNMM3u87NmX6TLvEDNJG5A9&currency=USD&disable-funding=sofort,card,credit,venmo,ideal,sepa,bancontact,eps,giropay,mercadopago,mybank,p24"></script>

    <script>
        paypal.Buttons({
            style: {
                color: 'blue',
                shape: 'rect',
            },

            createOrder: function (data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '10.00'
                        }
                    }]
                });
            },
            onApprove: function (data, actions) {

                return actions.order.capture().then(function (orderData) {
                    window.location.href = "{% url 'training:complete' %}";
                });
            }


        }).render('#paypal-button-container');
    </script>
    </body>

    </html>
{% endblock content %}

training/templates/training_delete.html
{% extends 'base.html' %}
{% block content %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Training Delete</title>
        <style>
            *, *:after, *:before {
                box-sizing: border-box;
                margin: 0;
                padding: 0;
            }

            body {
                background: #467fae;
                font-family: 'HelveticaNeue-Light', 'Helvetica Neue Light', 'Helvetica Neue', 'Helvetica', 'Arial', 'Lucida Grande', sans-serif;
            }

            @keyframes fade {
                from {
                    opacity: 0;
                    transform: translate(-50%, -50%) scale(0.8);
                }
                to {
                    opacity: 1;
                    transform: translate(-50%, -50%) scale(1);
                }
            }

            .confirm {
                position: absolute;
                top: 50%;
                left: 50%;
                transform: translate(-50%, -50%);
                width: 80%;
                min-width: 280px;
                max-width: 500px;
                height: auto;
                background: #E2E2E2;
                border-radius: 10px;
                padding: 0;
                margin: 0;
                border-top: 1px solid white;
                animation: fade 1s ease 1 forwards;
            }

            .confirm h1 {
                text-align: center;
                font-size: 1.2rem;
                margin: 1.5rem 1rem 0.5rem;
            }

            .confirm p {
                text-align: center;
                font-size: 1rem;
                margin: 0 2rem 4.5rem;
            }

            .confirm button {
                background: transparent;
                border: none;
                color: #1678E5;
                height: 3rem;
                font-size: 1rem;
                width: 50%;
                position: absolute;
                bottom: 0;
                cursor: pointer;
            }

            .confirm button:nth-of-type(1) {
                border-top: 1px solid #B4B4B4;
                border-right: 1px solid #B4B4B4;
                left: 0;
                border-radius: 0 0 0 10px;
            }

            .confirm button:nth-of-type(2) {
                border-top: 1px solid #B4B4B4;
                right: 0;
                border-radius: 0 0 10px 0;
            }

            .confirm button:focus,
            .confirm button:hover {
                font-weight: bold;
                background: #EFEFEF;
            }

            .confirm button:active {
                background: #D6D6D6;
            }


        </style>
    </head>
    <body>
    <br><br><br>
    <form method="post">
        {% csrf_token %}
        <div class="confirm">
            <p style="padding: 20px"><b>are you sure you want to delete your Post?</b></p>
            <button>Cancel</button>
            <button autofocus>Confirm</button>
        </div>

    </form>
    </body>
    </html>
{% endblock content %}

training/templates/training_details.html
{% extends 'base.html' %}
{% block content %}
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <title>{{ training.title }}</title>
        <style>

            .card {
                box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
                transition: 0.3s;
                width: 40%;
                border-radius: 5px;
                margin: 0 auto;

                float: none;

                margin-bottom: 10px;

            }

            .card:hover {
                box-shadow: 0 8px 16px 0 rgba(0, 0, 0, 0.2);
            }


            .container {
                padding: 2px 16px;
            }

            .font_style {
                font-family: Georgia, "Times New Roman", Times, serif;

            }

            .style {
                color: #3141d5;
                font-size: 20px;
            }

            .modalBox {
                position: fixed;
                font-family: Arial, Helvetica, sans-serif;
                top: 0;
                right: 0;
                bottom: 0;
                left: 0;
                background: rgba(0, 0, 0, 0.8);
                color: black;
                z-index: 99999;
                opacity: 0;
                -webkit-transition: opacity 400ms ease-in;
                -moz-transition: opacity 400ms ease-in;
                transition: opacity 400ms ease-in;
                pointer-events: none;
            }

            .modalBox:target {
                opacity: 1;
                pointer-events: auto;
            }

            .modalBox > div {
                width: 400px;
                position: relative;
                margin: 10% auto;
                padding: 5px 20px 13px 20px;
                border-radius: 0px;
                background: white;
            }

        </style>
    </head>
    <body>
    <br>
    <br>
    <br>
    <div class="card">
        <div class="container shadow-lg" style="background-color: #c9e7ef">
            <p>
            <h6 class="font_style"><b class="style shadow-sm">Author: </b></h6>
            <b style="font-size: 18px"><a href="{{ training_to_display.author.get_user_id }}" >{{ training_to_display.author }}</a></b>
            </p>
            <p>
            <h6 class="font_style"><b class="style shadow-sm">title:</b></h6>
            <b style="font-size: 18px">{{ training_to_display.title }}</b>
            </p>
            <p>
            <h6 class="font_style"><b class="style shadow-sm">description:</b></h6>
            <b style="font-size: 18px"> {{ training_to_display.description }}</b>
            </p>
            <p>
            <h6 class="font_style"><b class="style shadow-sm">category:</b></h6>
            <b style="font-size: 18px"> {{ training_to_display.category }}</b>
            </p>
            <p>
            <h6 class="font_style"><b class="style shadow-sm">tag: </b></h6>
            {% for tag in training_to_display.tags.all %}
                <b style="font-size: 18px"> {{ tag.name }}</b>
            {% endfor %}
            </p>
            <h6 class="font_style"><b class="style shadow-sm">country:</b></h6>
            <b style="font-size: 18px">{{ training_to_display.country }}</b>
            </p>
            <p>
            <h6 class="font_style"><b class="style shadow-sm">price: </b></h6>
            <b style="font-size: 18px"> {{ training_to_display.price }}</b>
            </p>
            <p>
            <h6 class="font_style"><b class="style shadow-sm">email:</b></h6>
            <b style="font-size: 18px"> {{ training_to_display.email }}</b>
            </p>
            <p>
            <h6 class="font_style"><b class="style shadow-sm">phone_number: </b></h6>
            <b style="font-size: 18px">{{ training_to_display.phone_number }}</b>
            </p>
            <p>
            <h6 class="font_style"><b class="style shadow-sm">created:</b></h6>
            <b style="font-size: 18px"> {{ training_to_display.created }}</b>
            </p>
            <p>
            <h6 class="font_style"><b class="style shadow-sm">updated:</b></h6>
            <b style="font-size: 18px">{{ training_to_display.updated }}</b>
            </p>
            {% if request.user == training_to_display.author %}
                <a href="{{ training_to_display.get_absolute_delete_url }}">
                    <button type="button" class="btn btn-primary my-2 my-sm-0">Delete</button>
                </a>
                <a href="{{ training_to_display.get_absolute_edit_url }}">
                    <button type="button" class="btn btn-danger wmy-2 my-sm-0" style="margin-left: 10px">EDIT</button>
                </a>
                </div>
                </div>
                <br>
            {% endif %}
    </body>
    </html>
{% endblock content %}

training/templates/trainings_list.html
    {% extends 'base.html' %}
    {% block content %}
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <link rel="stylesheet"
                  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
            <title>Training</title>
            <style>
                .card {
                    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
                    transition: 0.3s;
                    width: 40%;
                    border-radius: 5px;
                }

                .card:hover {
                    box-shadow: 0 8px 16px 0 rgba(0, 0, 0, 0.2);
                }


                .container {
                    padding: 2px 16px;
                }


                body {
                    background-color: #b4d3e5;
                }

            </style>
        </head>
        <body>
        <br>
        <br>
        <br>
                <nav class="navbar navbar-light bg-light justify-content-between shadow-lg" style="padding: 20px ">
            <p>
            <form action="{% url 'training:search_training' %}" method="get" style="display:inline-table">


                <div>

                    <input name="search" type="search" id="search" placeholder="search something"
                           style="border-radius: 2%">

                    <select name="category_id" id="category_id">
                        <option value="0">None</option>
                        {% for category in categories %}
                            <option value="{{ category.id }}">{{ category.name }}</option>>
                        {% endfor %}

                    </select>
                    <select name="country_id" id="country_id">
                        <option value="0">None</option>
                        {% for country in countries %}
                            <option value="{{ country.id }}">{{ country.country }}</option>>
                        {% endfor %}

                    </select>
                    <button type="submit">Search</button>
                </div>

            </form>
            </p>
                </p>
                {% if request.user.is_authenticated %}
                    {% if not request.user.is_trainer %}
                    <a href="{% url 'training:payment' %}">
                        <button class="btn btn-outline-primary my-2 my-sm-0" type="button" style="margin-left: 10px">Become
                            A trainer
                        </button>
                    </a>
                    {% endif %}
                {% endif %}
                {% if request.user.is_trainer %}
                    <a href="{% url 'training:add_training' %}">
                        <button class="btn btn-outline-primary my-2 my-sm-0">Add training</button>
                    </a>
                {% endif %}
            </nav>
            <br>

        {% for training in trainings %}
            <div class="card" style="margin-left:30px">
                <div class="container">
                    <a><h4><a href="{{ training.get_absolute_url }}">{{ training.title }}</a></h4></a>
                    <p style="font-size: 18px"><b class="shadow-sm">Description</b> {{ training.description }}</p>

                    <p style="font-size: 18px"><b class="shadow-sm">BY:</b> <a href="{{ training.author.get_user_id }}"> {{ training.author }}</a></p>
                </div>
            </div>
            <br>
        {% endfor %}
        <br>
        </body>
        </html>
    {% endblock content %}