RTS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib import admin
from account.views import base


urlpatterns = [
    path('', base, name="home"),
    path('admin/', admin.site.urls),
    path('account/', include("account.urls")),
    path('cv/', include("cv.urls")),
    path('jobs/', include("jobs.urls")),
    path('careeradvice/', include("careeradvice.urls")),
    path('training/', include("training.urls")),
    path('api/', include("generics.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cv/urls.py
from django.urls import path
from . import views
from generics.views import preview

# Namespace for CV app.
app_name = "cv"

# CV urls.
urlpatterns = [
    # Home's urls
    path('', views.have_cv, name="home"),
    # CV's urls.
    path('cv_show/', views.show, name='cv_show'),
    path('cv_make/', views.create, name='create'),
    path('delete/', views.delete, name='delete_cv'),
    path('edit/', views.edit, name='edit'),
    path('preview/<cv_id>/', preview, name='preview'),
]

generics/urls.py
from django.urls import path
from . import views
app_name = "generics"

urlpatterns = [
    path('pdf/', views.pdf, name='ppdf')
]

training/urls.py
from django.urls import path
from . import views


# Create a name space for the training application
app_name = "training"

# Training's urls
urlpatterns = [
    path('', views.trainings_list, name='trainings_list'),
    path('<int:training_id>/', views.training_details, name='training_details'),
    path('add/', views.add_training, name='add_training'),
    path('edit/<training_id>/', views.training_edit, name='edit_training'),
    path('delete/<training_id>/', views.training_delete, name='training_delete'),
    path('payment/', views.payment, name='payment'),
    path('complete/', views.payment_complete, name='complete'),
    path('search_result/', views.search_training, name='search_training')
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from django.urls import reverse

Gender = (
    ('male', "Male"),
    ('female', "Female"),

)


class Profile(AbstractUser):
    is_company = models.BooleanField(default=False)
    is_employee = models.BooleanField(default=False)
    is_trainer = models.BooleanField(default=False)
    # Holds the user's bio
    bio = models.CharField(max_length=255, blank=True)
    # Holds the user's photo
    photo = models.ImageField(upload_to="users_profile_photo/", blank=True,
                              default="users_profile_photo/default_profile_photo.jpg")
    # Holds the user's phone number
    phone_number = PhoneNumberField(unique=True, null=True, blank=True)

    def pic(self):
        return self.photo

    def get_user_id(self):
        return reverse('account:show_profile', args=[self.pk])


class Company(models.Model):
    # If the company was deleted the profile will be deleted as well.
    user = models.OneToOneField(Profile, on_delete=models.CASCADE, primary_key=True, related_name='company')
    # Holds the user's website
    website = models.URLField(max_length=200)
    # Holds the location
    location = models.CharField(max_length=200)

    def __str__(self):
        return self.website


class Employee(models.Model):
    # If the employee was deleted the profile will be deleted as well.
    user = models.OneToOneField(Profile, on_delete=models.CASCADE, primary_key=True, related_name='employee')
    # Holds the user's date of birth
    date_of_birth = models.DateField()
    # Holds the user's gender
    gender = models.CharField(choices=Gender, max_length=6)

    def __str__(self):
        return self.gender

    def name(self):
        return f"{self.user.username}'s Profile"

cv/models.py
from django.db import models
from django.conf import settings
from phonenumber_field.modelfields import PhoneNumberField
from django.urls import reverse
from generics.models import Experiences, Educations, Skills, Countries, Grades


choice = (("Male", "Male"), ("Female", "Female"))


# Create your models here.
class CV(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=False)
    first_name = models.CharField(max_length=256, blank=False)
    last_name = models.CharField(max_length=256, blank=False)
    email = models.EmailField(blank=False)
    picture = models.ImageField(upload_to="cv/", blank=False)
    gender = models.CharField(blank=False, choices=choice, max_length=15, default="Male")
    interests = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.first_name

    def get_url(self):
        return reverse('cv:preview', args=[self.id])


class EmpExperience(models.Model):
    experience = models.ForeignKey(Experiences, on_delete=models.CASCADE, blank=False, unique=False)
    start = models.DateField(blank=False)
    end = models.DateField(blank=False)
    cv = models.ForeignKey(CV, on_delete=models.CASCADE, blank=False)


class EmpEducations(models.Model):
    education = models.ForeignKey(Educations, on_delete=models.CASCADE, blank=False, unique=False)
    date = models.DateField(blank=False)
    cv = models.ForeignKey(CV, on_delete=models.CASCADE, blank=False)


class EmpSkills(models.Model):
    grade = models.ForeignKey(Grades, on_delete=models.CASCADE, blank=False)
    skill = models.ForeignKey(Skills, on_delete=models.CASCADE, blank=False, unique=False)
    cv = models.ForeignKey(CV, on_delete=models.CASCADE, blank=False)


class EmpLocations(models.Model):
    cv = models.ForeignKey(CV, on_delete=models.CASCADE, blank=False)
    country = models.ForeignKey(Countries, on_delete=models.CASCADE, blank=False)


class EmpPhoneNumber(models.Model):
    cv = models.ForeignKey(CV, on_delete=models.CASCADE, blank=False)
    phone_number = PhoneNumberField(unique=True, null=True, blank=True)

cv/forms.py
from django import forms
from .models import CV, EmpEducations, EmpSkills, EmpExperience, EmpLocations, EmpPhoneNumber
from django.forms import modelformset_factory


class CvForm(forms.ModelForm):
    class Meta:
        model = CV
        # List of input to make cv.
        fields = ("first_name", "last_name", "email", "gender", "picture", "interests")


class EmpEducationsForm(forms.ModelForm):
    class Meta:
        model = EmpEducations
        fields = ("education", "date")
        help_texts = {"date": "yyyy-mm-dd"}


class EmpSkillsForm(forms.ModelForm):
    class Meta:
        model = EmpSkills
        fields = ("skill", "grade")


class EmpExperienceForm(forms.ModelForm):
    class Meta:
        model = EmpExperience
        fields = ("experience", "start", "end")
        help_texts = {"start": "yyyy-mm-dd", "end": "yyyy-mm-dd"}


class EmpLocationsForm(forms.ModelForm):
    class Meta:
        model = EmpLocations
        fields = ("country",)


class EmpPhoneNumberForm(forms.ModelForm):
    class Meta:
        model = EmpPhoneNumber
        fields = ("phone_number",)


SkillFormset = modelformset_factory(
    model=EmpSkills,
    form=EmpSkillsForm,
    extra=1,
    can_delete=True,
    can_delete_extra=True,
)


ExperienceFormset = modelformset_factory(
    EmpExperience,
    form=EmpExperienceForm,
    extra=1,
    can_delete=True,
    can_delete_extra=True,
)

EducationsFormset = modelformset_factory(
    EmpEducations,
    form=EmpEducationsForm,
    extra=1,
    can_delete=True,
    can_delete_extra=True,
)

LocationsFormset = modelformset_factory(
    EmpLocations,
    form=EmpLocationsForm,
    extra=1,
    can_delete=True,
    can_delete_extra=True,
    max_num=1,
)

PhoneNumberFormset = modelformset_factory(
    EmpPhoneNumber,
    form=EmpPhoneNumberForm,
    extra=1,
    can_delete=True,
    can_delete_extra=True,
)

cv/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from generics.views import save, delete_duplicate
from .models import CV, EmpExperience, EmpEducations, EmpSkills, \
    EmpLocations, EmpPhoneNumber
from .forms import CvForm, SkillFormset, EducationsFormset, \
    ExperienceFormset, LocationsFormset, PhoneNumberFormset
from jobs.models import JobApply
from generics.views import compare_cv


def have_cv(request):
    if request.user.is_employee:
        # get all CVs in the model.
        cv = CV.objects.filter(user=request.user)
        if cv:
            return redirect('cv:cv_show')
        else:
            return redirect('cv:create')


#####################################################################################


def show(request):
    """Show user's CV """
    # Make query to user's CV.
    cv = get_object_or_404(CV, user=request.user)
    experiences = EmpExperience.objects.filter(cv=cv).order_by('id')
    skills = EmpSkills.objects.filter(cv=cv).order_by('id')
    educations = EmpEducations.objects.filter(cv=cv).order_by('id')
    locations = EmpLocations.objects.filter(cv=cv).order_by('id')
    phone_number = EmpPhoneNumber.objects.filter(cv=cv).order_by('id')

    context = {}
    same_user = False
    if cv.user == request.user:
        same_user = True
        # Save user picture in variable.
        image = cv.picture

        # A dictionary to send CV and user's picture to the HTML.
        context = {"cv": cv, "image": image, "same_user": same_user,
                   "experiences": experiences, "skills": skills,
                   "educations": educations, "locations": locations,
                   "phone_number": phone_number,
                   }
    # Everything went well render send the user to the posted reviews page.
    return render(request, "show.html", context)


def create(request):
    """A view to make new CV."""
    # Is it a post request ?
    if request.method == 'POST':
        # make instance of CV.
        make_cv_form = CvForm(request.POST, files=request.FILES)
        experience_formset = ExperienceFormset(request.POST)
        education_formset = EducationsFormset(request.POST)
        skill_formset = SkillFormset(request.POST)
        location_formset = LocationsFormset(request.POST)
        phone_number_formset = PhoneNumberFormset(request.POST)

        experience_formset.prefix = "experience"
        education_formset.prefix = "education"
        skill_formset.prefix = "skill"
        location_formset.prefix = "location"
        phone_number_formset.prefix = "phone-number"

        # The data are valid ?
        if make_cv_form.is_valid() and experience_formset.is_valid() \
                and skill_formset.is_valid() and education_formset.is_valid() \
                and location_formset.is_valid() and phone_number_formset.is_valid():
            # Create a new CV object but don't save it to the database just yet.
            new_cv_form = make_cv_form.save(commit=False)
            # request user ID to put it in CV.
            new_cv_form.user = request.user
            # is image included.
            if request.FILES:
                # add the image to CV.
                new_cv_form.image = request.FILES["picture"]

            save(
                request, new_cv_form, skill_formset,
                experience_formset, education_formset,
                location_formset, phone_number_formset
            )

            skills = EmpSkills.objects.filter(cv=new_cv_form)
            experiences = EmpExperience.objects.filter(cv=new_cv_form)
            educations = EmpEducations.objects.filter(cv=new_cv_form)

            delete_duplicate(experiences, educations, skills)

            return redirect('cv:home')
    else:
        # create empty CV.
        make_cv_form = CvForm()
        experience_formset = ExperienceFormset(queryset=EmpExperience.objects.none())
        education_formset = EducationsFormset(queryset=EmpEducations.objects.none())
        skill_formset = SkillFormset(queryset=EmpSkills.objects.none())
        location_formset = LocationsFormset(queryset=EmpLocations.objects.none())
        phone_number_formset = PhoneNumberFormset(queryset=EmpPhoneNumber.objects.none())

        experience_formset.prefix = "experience"
        education_formset.prefix = "education"
        skill_formset.prefix = "skill"
        location_formset.prefix = "location"
        phone_number_formset.prefix = "phone-number"

    # a dictionary that hold form of CV.
    context = {"make_cv_form": make_cv_form, "experience_formset": experience_formset,
               "education_formset": education_formset, "skill_formset": skill_formset,
               "location_formset": location_formset, "phone_number_formset": phone_number_formset}
    # to represent make_cv page.
    return render(request, "create.html", context)


def delete(request):
    """Method to delete CV"""
    # To get the CV's id.
    cv_to_delete = get_object_or_404(CV, user=request.user)
    applies_to_delete = None
    have_applies = False
    # Check if the one requesting is the CV's owner.
    if request.user != cv_to_delete.user:
        return HttpResponse("You don't own this CV!")
    if JobApply.objects.filter(user=request.user).count() != 0:
        have_applies = True
    # Is it a post request ? and checks if its by the owner himself.
    if request.method == "POST":
        for apply in JobApply.objects.filter(user=request.user):
            apply.delete()
        # If so delete the CV.
        cv_to_delete.delete()
        # Return to CV page.
        return redirect('account:profile')
    context = {"have_applies": have_applies}
    return render(request, "delete.html", context)


def edit(request):
    cv = get_object_or_404(CV, user=request.user)
    # Is it a post request ?
    if request.method == 'POST':
        # make instance of CV.
        make_cv_form = CvForm(data=request.POST, files=request.FILES, instance=cv)
        experience_formset = ExperienceFormset(request.POST, queryset=EmpExperience.objects.filter(cv=cv))
        education_formset = EducationsFormset(request.POST, queryset=EmpEducations.objects.filter(cv=cv))
        skill_formset = SkillFormset(request.POST, queryset=EmpSkills.objects.filter(cv=cv))
        location_formset = LocationsFormset(request.POST, queryset=EmpLocations.objects.filter(cv=cv))
        phone_number_formset = PhoneNumberFormset(request.POST, queryset=EmpPhoneNumber.objects.filter(cv=cv))

        experience_formset.prefix = "experience"
        education_formset.prefix = "education"
        skill_formset.prefix = "skill"
        location_formset.prefix = "location"
        phone_number_formset.prefix = "phone-number"

        # The data are valid ?
        if make_cv_form.is_valid() and skill_formset.is_valid() \
                and location_formset.is_valid() and phone_number_formset.is_valid() \
                and education_formset.is_valid() and experience_formset.is_valid():
            # Create a new CV object but don't save it to the database just yet.
            new_cv_form = make_cv_form.save(commit=False)

            save(
                request, new_cv_form, skill_formset,
                experience_formset, education_formset,
                location_formset, phone_number_formset,
            )

            skills = EmpSkills.objects.filter(cv=new_cv_form)
            experiences = EmpExperience.objects.filter(cv=new_cv_form)
            educations = EmpEducations.objects.filter(cv=new_cv_form)

            delete_duplicate(experiences, educations, skills)

            applies = JobApply.objects.filter(user=cv.user)

            for apply in applies:
                apply.evaluation = compare_cv(request, apply.job_id, apply.user)
                apply.save()

            return redirect('cv:cv_show')
    else:
        # create empty CV.
        make_cv_form = CvForm(instance=cv)
        experience_formset = ExperienceFormset(queryset=EmpExperience.objects.filter(cv=cv))
        education_formset = EducationsFormset(queryset=EmpEducations.objects.filter(cv=cv))
        skill_formset = SkillFormset(queryset=EmpSkills.objects.filter(cv=cv))
        location_formset = LocationsFormset(queryset=EmpLocations.objects.filter(cv=cv))
        phone_number_formset = PhoneNumberFormset(queryset=EmpPhoneNumber.objects.filter(cv=cv))

        experience_formset.prefix = "experience"
        education_formset.prefix = "education"
        skill_formset.prefix = "skill"
        location_formset.prefix = "location"
        phone_number_formset.prefix = "phone-number"

    # a dictionary that hold form of CV.
    context = {"make_cv_form": make_cv_form, "experience_formset": experience_formset,
               "education_formset": education_formset, "skill_formset": skill_formset,
               "location_formset": location_formset, "phone_number_formset": phone_number_formset}
    # to represent make_cv page.
    return render(request, "edit.html", context)

cv/templates/create.html
{% extends 'base.html' %}
{% block content %}
<head>
    <title>Make CV</title>
  <style>
        form{
            border:4px solid black;
            margin: 0 auto;
            padding: 40px;
            width: fit-content;
        }
    </style>
</head>
<body>
    <br>
    <br>
    <br>
<form id="form-container" method="POST" class="card shadow-lg container" enctype="multipart/form-data" style="border-width: 0px">
     {% csrf_token %}
    <h3>personal information</h3>
     {{ make_cv_form.as_p }}
    <hr>
    <h3>experiences</h3>
        <p>____________</p> 
        {{ experience_formset.management_form }}
        {% for form in experience_formset %}
        <div class="experience-form">
        {{form.as_p}}
        <p>____________</p>
            </div>
        {% endfor %}
    <button id="add-experience-form" class="btn btn-outline-primary col-3" type="button">Add experience</button>

    <hr>
    <h3>educations</h3>
<p>____________</p>
        {{ education_formset.management_form }}
        {% for form in education_formset %}
        <div class="education-form">
        {{form.as_p}}
        <p>____________</p>
        </div>
        {% endfor %}
    <button id="add-education-form" class="btn btn-outline-primary col-3" type="button">Add education</button>

    <hr>
    <h3>skills</h3>
<p>____________</p>
        {{skill_formset.management_form}}

        {% for form in skill_formset %}
        <div class="skill-form">
        {{form.as_p}}
        <p>____________</p>
        </div>
        {% endfor %}

    <button id="add-skill-form" class="btn btn-outline-primary col-3"  type="button">Add skill</button>

    <hr>
    <h3>location address</h3>
<p>____________</p>
{{ location_formset.management_form }}
        {% for form in location_formset %}
        <div class="location-form">
        {{form.as_table}}
        <p>____________</p>
        </div>
        {% endfor %}
    <br>

    <h3>Phone number</h3>
<p>____________</p>
        {{ phone_number_formset.management_form }}
        {% for form in phone_number_formset %}
        <div class="phone-number-form">
        {{form.as_p}}
        <p>____________</p>
        </div>
        {% endfor %}
    <button id="add-phone-number-form" class="btn btn-outline-primary col-3" type="button">Add phone number</button>
        <br>
            <div style="align-self: end" class="col-4">
            <a href="{% url 'cv:home' %}">
                <button type="submit" class=" btn btn-block btn-primary col-5" style="align-self: end">Create</button>
            </a>
            </div>


</div>
</form>
    <script>
        let container = document.querySelector("#form-container")

        let skillForm = document.querySelectorAll(".skill-form")
        let skillAddButton = document.querySelector("#add-skill-form")
        let totalSkillForms = document.querySelector("#id_skill-TOTAL_FORMS")
        let skillFormNum = skillForm.length-1
        skillAddButton.addEventListener('click', addSkillForm)

        let educationForm = document.querySelectorAll(".education-form")
        let educationAddButton = document.querySelector("#add-education-form")
        let totalEducationForms = document.querySelector("#id_education-TOTAL_FORMS")
        let educationFormNum = skillForm.length-1
        educationAddButton.addEventListener('click', addEducationForm)

        let experienceForm = document.querySelectorAll(".experience-form")
        let experienceAddButton = document.querySelector("#add-experience-form")
        let totalExperienceForms = document.querySelector("#id_experience-TOTAL_FORMS")
        let experienceFormNum = experienceForm.length-1
        experienceAddButton.addEventListener('click', addExperienceForm)

        let phoneNumberForm = document.querySelectorAll(".phone-number-form")
        let phoneNumberAddButton = document.querySelector("#add-phone-number-form")
        let totalPhoneNumberForms = document.querySelector("#id_phone-number-TOTAL_FORMS")
        let phoneNumberFormNum = phoneNumberForm.length-1
        phoneNumberAddButton.addEventListener('click', addPhoneNumberForm)

        let locationForm = document.querySelectorAll(".location-form")
        let locationAddButton = document.querySelector("#add-location-form")
        let totalLocationForms = document.querySelector("#id_location-TOTAL_FORMS")
        let locationFormNum = locationForm.length-1
        locationAddButton.addEventListener('click', addLocationForm)

        function addEducationForm(e){
            e.preventDefault()

            let newForm = educationForm[0].cloneNode(true)
            let formRegex = RegExp(`education-(\\d){1}-`,'g')

            educationFormNum++
            newForm.innerHTML = newForm.innerHTML.replace(formRegex, `education-${educationFormNum}-`)
            container.insertBefore(newForm, educationAddButton)

            totalEducationForms.setAttribute('value', `${educationFormNum+1}`)
        }

        function addSkillForm(e){
            e.preventDefault()

            let newForm = skillForm[0].cloneNode(true)
            let formRegex = RegExp(`skill-(\\d){1}-`,'g')

            skillFormNum++
            newForm.innerHTML = newForm.innerHTML.replace(formRegex, `skill-${skillFormNum}-`)
            container.insertBefore(newForm, skillAddButton)

            totalSkillForms.setAttribute('value', `${skillFormNum+1}`)
        }

         function addExperienceForm(e){
            e.preventDefault()

            let newForm = experienceForm[0].cloneNode(true)
            let formRegex = RegExp(`experience-(\\d){1}-`,'g')

            experienceFormNum++
            newForm.innerHTML = newForm.innerHTML.replace(formRegex, `experience-${experienceFormNum}-`)
            container.insertBefore(newForm, experienceAddButton)

            totalExperienceForms.setAttribute('value', `${experienceFormNum+1}`)
        }
        function addPhoneNumberForm(e){
            e.preventDefault()

            let newForm = phoneNumberForm[0].cloneNode(true)
            let formRegex = RegExp(`phone-number-(\\d){1}-`,'g')

            phoneNumberFormNum++
            newForm.innerHTML = newForm.innerHTML.replace(formRegex, `phone-number-${phoneNumberFormNum}-`)
            container.insertBefore(newForm, phoneNumberAddButton)

            totalPhoneNumberForms.setAttribute('value', `${phoneNumberFormNum+1}`)
        }
        function addLocationForm(e){
            e.preventDefault()

            let newForm = locationForm[0].cloneNode(true)
            let formRegex = RegExp(`location-(\\d){1}-`,'g')

            locationFormNum++
            newForm.innerHTML = newForm.innerHTML.replace(formRegex, `location-${locationFormNum}-`)
            container.insertBefore(newForm, locationAddButton)

            totalLocationForms.setAttribute('value', `${locationFormNum+1}`)
        }
    </script>
<br>
<br>
</body>
{% endblock content %}

cv/templates/show.html
{% extends 'base.html' %}{% load static %}
{% block content %}
    <html lang="en" xmlns="http://www.w3.org/1999/html">
    <head>
        <title>YOUR CV</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
        <link href="bootstrap.css">
        <style>
            .box{
                border: 4px solid #000000;
                margin: 0 auto;
                }
            h3{
                color: black;
            }
            /* Popup box BEGIN */
.hover_bkgr_fricc{
    background:rgba(0,0,0,.4);
    cursor:pointer;
    display:none;
    height:100%;
    position:fixed;
    text-align:center;
    top:0;
    left: 0px;
    width:100%;
    z-index:10000;
}
.hover_bkgr_fricc .helper{
    display:inline-block;
    height:100%;
    vertical-align:middle;
}
.hover_bkgr_fricc > div {
    background-color: #fff;
    box-shadow: 10px 10px 60px #555;
    display: inline-block;
    height: auto;
    max-width: 551px;
    min-height: 100px;
    vertical-align: middle;
    width: 60%;
    position: relative;
    border-radius: 8px;
    padding: 15px 5%;
}
.popupCloseButton {
    background-color: #fff;
    border: 3px solid #999;
    border-radius: 50px;
    cursor: pointer;
    display: inline-block;
    font-family: arial;
    font-weight: bold;
    position: absolute;
    top: -20px;
    right: -20px;
    font-size: 25px;
    line-height: 30px;
    width: 30px;
    height: 30px;
    text-align: center;
}
.popupCloseButton:hover {
    background-color: #ccc;
}
.trigger_popup_fricc {
    cursor: pointer;
    font-size: 20px;
    margin: 20px;
    display: inline-block;
    font-weight: bold;
}
/* Popup box BEGIN */
        </style>
    </head>
    <body>
        <br>
    <br>
    <br>
                <div class="card container shadow-lg" style="align-self: center; border-radius: 2%" >
                <div class="row" style="padding: 20px">
                <div class="col-lg-6 col-md-6 col-sm-6 kill left">
                    <br>

                    <div style="margin-top:-15px ">
                        {% if image %}
                         <a href="{{ image.url }}" >
                             <img src="{{ image.url }}" height="180px" width="180px" style="border-radius: 2%">
                         </a>
                        {% endif %}
                    </div>

                        <br>
                        <h1>{{ cv.first_name }} {{ cv.last_name }}</h1>
                        <br>

                        <h3 style="color: red">EMAIL</h3>
                        <div class="text default" style="display: inline-block">
                        <a href="http://{{ cv.email }}" ><p style="font-size: larger">{{ cv.email }}</p></a>
                        </div >
                        <br>
                        <h6 style="color: red">Gender: {{ cv.gender }}</h6>
                        <br>

                        <h3 style="color: red">EXPERIENCES</h3>
                        {% for ex in experiences %}
                            <p>{{ ex.experience }}: <p style="color: #ff0000">{{ ex.start }} to {{ ex.end }}</p></p>

                        {% endfor %}
                        <br>
                        <h3 style="color: red">EDUCATIONS</h3>
                        {% for ed in educations %}
                            <h6>{{ed.education}}: {{ ed.date }}</h6>
                        {% endfor %}
                        <br>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 kill right" style="border-left:0.5px solid red;">
                        <h3 style="color: red">Skills</h3>
                        {% for sk in skills %}
                            <h6>{{ sk.skill }} : {{ sk.grade }}</h6>
                        {% endfor %}
                        <br>

                        <h4 style="color: red">Location</h4>
                        {% for l in locations %}
                            <h6>{{ l.country }}</h6>
                        {% endfor %}
                        <br>
                        <h3 style="color: #ff0000">Interests</h3>
                        <p>{{ cv.interests }}</p>

                        <hr>
                            <p style="color: red">Phone Numbers</p>
                        {% for p in phone_number %}
                            <p>{{ p.phone_number }}</p>
                        {% endfor %}
                        <hr>
                        <h7>Created in {{ cv.created }}</h7>
                <br>

                        {% if cv.updated != cv.created %}
                            <h7 style="color: #007f00">Updated in {{ cv.updated }} </h7>
                        {% endif %}

                <br>
                </div>
                </div>
                <div style="align-self: end">
                    <form action="{{ cv.get_url }}" method="get" style="align-self: end">
                        {% if request.user.is_trainer %}
                    <select name="color" id="color">
                        <option value="blue">blue</option>
                        <option value="green">green</option>
                        <option value="maroon">maroon</option>
                        <option value="steelblue">steelblue</option>
                        <option value="violet">violet</option>
                    </select>

<button type="submit" class="btn btn-primary">Preview</button>



<a href="{% url 'generics:ppdf' %}"> <input type="button" class=" btn btn-primary" value="Download As PDF" ></a>
                            {% else %}
                            <a href="{% url 'training:payment' %}">
                    <button class="btn btn-outline-primary my-2 my-sm-0" type="button" style="margin-left: 10px">Become
                        A trainer
                    </button>
                </a>
                        {% endif %}

                        <a href="{% url 'cv:edit' %}"><input class="btn btn-primary" style="max-width: 55px" value="Edit"></a>
                        <a href="{% url 'cv:delete_cv' %}">
                                <input type="button" value="Delete" class=" btn  btn-primary">
                            </a>
                        </form>



                        </div>
                <br>
                </div>
<br>
<br>
</body>
</html>
{% endblock content %}