RTS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib import admin
from account.views import base


urlpatterns = [
    path('', base, name="home"),
    path('admin/', admin.site.urls),
    path('account/', include("account.urls")),
    path('cv/', include("cv.urls")),
    path('jobs/', include("jobs.urls")),
    path('careeradvice/', include("careeradvice.urls")),
    path('training/', include("training.urls")),
    path('api/', include("generics.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cv/urls.py
from django.urls import path
from . import views
from generics.views import preview

# Namespace for CV app.
app_name = "cv"

# CV urls.
urlpatterns = [
    # Home's urls
    path('', views.have_cv, name="home"),
    # CV's urls.
    path('cv_show/', views.show, name='cv_show'),
    path('cv_make/', views.create, name='create'),
    path('delete/', views.delete, name='delete_cv'),
    path('edit/', views.edit, name='edit'),
    path('preview/<cv_id>/', preview, name='preview'),
]

jobs/urls.py
from django.urls import path
from . import views
app_name = "jobs"
urlpatterns = [
    path('', views.posts, name='post_list'),
    path('add_job/', views.add_job, name='add_job'),
    path('search_job/', views.search_job, name='search_job'),
    path('<job_id>/', views.job_details, name="job_details"),
    path('edit/<int:job_id>/', views.edit_job, name='job_edit'),
    path('add_apply/<job_id>/', views.add_apply, name='add_apply'),
    path('delete/<int:job_id>/', views.delete_job, name="job_delete"),
    path('show_applies/<job_id>/', views.show_applies, name='show_applies'),
    path('apply_details/<int:apply_id>/', views.apply_details, name='apply_details')

]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from django.urls import reverse

Gender = (
    ('male', "Male"),
    ('female', "Female"),

)


class Profile(AbstractUser):
    is_company = models.BooleanField(default=False)
    is_employee = models.BooleanField(default=False)
    is_trainer = models.BooleanField(default=False)
    # Holds the user's bio
    bio = models.CharField(max_length=255, blank=True)
    # Holds the user's photo
    photo = models.ImageField(upload_to="users_profile_photo/", blank=True,
                              default="users_profile_photo/default_profile_photo.jpg")
    # Holds the user's phone number
    phone_number = PhoneNumberField(unique=True, null=True, blank=True)

    def pic(self):
        return self.photo

    def get_user_id(self):
        return reverse('account:show_profile', args=[self.pk])


class Company(models.Model):
    # If the company was deleted the profile will be deleted as well.
    user = models.OneToOneField(Profile, on_delete=models.CASCADE, primary_key=True, related_name='company')
    # Holds the user's website
    website = models.URLField(max_length=200)
    # Holds the location
    location = models.CharField(max_length=200)

    def __str__(self):
        return self.website


class Employee(models.Model):
    # If the employee was deleted the profile will be deleted as well.
    user = models.OneToOneField(Profile, on_delete=models.CASCADE, primary_key=True, related_name='employee')
    # Holds the user's date of birth
    date_of_birth = models.DateField()
    # Holds the user's gender
    gender = models.CharField(choices=Gender, max_length=6)

    def __str__(self):
        return self.gender

    def name(self):
        return f"{self.user.username}'s Profile"

jobs/models.py
from django.conf import settings
from taggit.managers import TaggableManager
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField
from generics.models import *


# Create your models here.
class JobPost(models.Model):
    # A foreign key to the user when the user is deleted the corresponding threads are deleted as well
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="jobpost_created", on_delete=models.CASCADE)
    # The review's title
    heading = models.CharField(max_length=110)
    # A field to make SEO friendly links
    slug = models.SlugField(max_length=110)
    # An opening describes what this thread is about
    description = models.TextField()
    # The time and date the review was posted and it's added automatically
    created = models.DateTimeField(auto_now_add=True)
    # Updates the time when the thread is updated
    updated = models.TimeField(auto_now_add=True)
    # Tags to mark the post
    tags = TaggableManager()
    gender_choices = (('male', 'Male'), ('female', 'Female'))
    gender = models.CharField(choices=gender_choices, max_length=7)
    # poster email
    email = models.EmailField()
    job_type_choices = (('full_time', 'Full_Time'), ('half_time', 'Half_Time'))
    job_type = models.CharField(choices=job_type_choices, max_length=10)
    salary = models.DecimalField(decimal_places=2, max_digits=8)
    is_active = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=False)

    def get_absolute_url(self):
        """Returns a jobpost object URL"""
        # Build and return a unique and SEO friendly URL for a Thread object
        return reverse('jobs:job_details', args=[self.id])

    def edit_url(self):
        return reverse('jobs:job_edit', args=[self.id])

    def delete_url(self):
        return reverse('jobs:job_delete', args=[self.id])

    def apply_url(self):
        return reverse('jobs:add_apply', args=[self.id])

    def applies_url(self):
        return reverse('jobs:show_applies', args=[self.id])

    def __str__(self):
        return self.heading


class Locations(models.Model):
    job = models.ForeignKey(JobPost, on_delete=models.CASCADE, blank=False)
    country = models.ForeignKey(Countries, on_delete=models.CASCADE, blank=False)

    def delete_url(self):
        return reverse('jobs:job_delete', args=[self.id])


class JobApply(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=False)
    job = models.ForeignKey(JobPost, on_delete=models.CASCADE, blank=False)
    note = models.TextField()
    evaluation = models.IntegerField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("jobs:apply_details", args=[self.id])

    def get_job_url(self):
        return reverse("jobs:job_details", args=[self.job.id])

    def delete_url(self):
        return reverse('account:delete_apply', args=[self.id])


class RequiredExperience(models.Model):
    job = models.ForeignKey(JobPost, on_delete=models.CASCADE, blank=False)
    experience = models.ForeignKey(Experiences, on_delete=models.CASCADE, blank=False, unique=False)

    def delete_url(self):
        return reverse('jobs:job_delete', args=[self.id])


class RequiredEducation(models.Model):
    job = models.ForeignKey(JobPost, on_delete=models.CASCADE, blank=False)
    education = models.ForeignKey(Educations, on_delete=models.CASCADE, blank=False, unique=False)

    def delete_url(self):
        return reverse('jobs:job_delete', args=[self.id])


class RequiredSkills(models.Model):
    job = models.ForeignKey(JobPost, on_delete=models.CASCADE, blank=False)
    skill = models.ForeignKey(Skills, on_delete=models.CASCADE, blank=False, unique=False)

    def delete_url(self):
        return reverse('jobs:job_delete', args=[self.id])


class PhoneNumber(models.Model):
    job = models.ForeignKey(JobPost, on_delete=models.CASCADE, blank=False)
    phone_number = PhoneNumberField(unique=False, null=True, blank=True)

    def delete_url(self):
        return reverse('jobs:job_delete', args=[self.id])

jobs/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse

from account.models import Profile
from generics.views import compare_cv
from cv.views import delete_duplicate
from .forms import *
from django.utils.text import slugify
from cv.models import CV, EmpExperience, EmpEducations, EmpSkills, EmpLocations, EmpPhoneNumber
from django.db.models import Q
from generics.models import Category, Countries


# Create your views here.
def search_job(request):
    results = []
    categories = Category.objects.all()
    countries = Countries.objects.all()
    sal_category = Category()
    sal_country = Countries()
    query = None
    if request.method == "GET":
        query = request.GET.get('search')
        category = request.GET.get("category_id")
        country = request.GET.get("country_id")

        if category:
            sal_category = Category.objects.filter(pk=category)

        if country:
            sal_country = Countries.objects.filter(pk=country)

        if query != '':
            if JobPost.objects.filter(Q(tags__name__icontains=query)):
                results = JobPost.objects.filter(Q(tags__name=query))
            else:
                results = JobPost.objects.filter(Q(heading__icontains=query) |
                                                 Q(description__icontains=query))

        elif query == '':
            results = JobPost.objects.all().order_by('-id')

        if category != "0":
            results = results.filter(Q(category__name=sal_category[0].name))

        if country != "0":
            results = results.filter(Q(locations__country__country=sal_country[0].country))

    return render(request, 'job_post.html', {'jobs': results, 'categories': categories, 'countries': countries})


def posts(request):
    user_photo = Profile.objects.all().order_by('-id')
    categories = Category.objects.all()
    countries = Countries.objects.all()
    job = JobPost.objects.all().order_by('-id')

    context = {'jobs': job, "categories": categories, 'countries': countries}
    return render(request, 'job_post.html', context)


def add_job(request):
    if request.method == 'POST':
        job_form = JobPostForm(request.POST)
        experience_formset = ExperienceFormset(request.POST)
        education_formset = EducationFormset(request.POST)
        skill_formset = SkillFormset(request.POST)
        phone_number_formset = PhoneNumberFormset(request.POST)
        locations_formset = LocationsFormset(request.POST)
        experience_formset.prefix = "experience"
        education_formset.prefix = "education"
        skill_formset.prefix = "skill"
        phone_number_formset.prefix = "phone"
        locations_formset.prefix = "location"

        # The data are valid ?
        if job_form.is_valid() and experience_formset.is_valid() and education_formset.is_valid() \
                and skill_formset.is_valid() and locations_formset.is_valid() \
                and phone_number_formset.is_valid():
            new_job_form = job_form.save(commit=False)
            new_job_form.author = request.user
            new_job_form.slug = slugify(new_job_form.heading)

            for experience_form in experience_formset:
                new_experience_form = experience_form.save(commit=False)
                new_experience_form.job = new_job_form

            for education_form in education_formset:
                new_education_form = education_form.save(commit=False)
                new_education_form.job = new_job_form

            for skill_form in skill_formset:
                new_skill_form = skill_form.save(commit=False)
                new_skill_form.job = new_job_form

            for locations_form in locations_formset:
                new_locations_form = locations_form.save(commit=False)
                new_locations_form.job = new_job_form

            for phone_number_form in phone_number_formset:
                new_phone_number_form = phone_number_form.save(commit=False)
                new_phone_number_form.job = new_job_form

            new_job_form.save()
            job_form.save_m2m()

            experience_formset.save()
            education_formset.save()
            skill_formset.save()
            locations_formset.save()
            phone_number_formset.save()

            return redirect('jobs:post_list')

    else:
        job_form = JobPostForm()

        experience_formset = ExperienceFormset(queryset=RequiredExperience.objects.none())
        education_formset = EducationFormset(queryset=RequiredEducation.objects.none())
        skill_formset = SkillFormset(queryset=RequiredSkills.objects.none())
        locations_formset = LocationsFormset(queryset=Locations.objects.none())
        phone_number_formset = PhoneNumberFormset(queryset=PhoneNumber.objects.none())

        experience_formset.prefix = "experience"
        education_formset.prefix = "education"
        skill_formset.prefix = "skill"
        locations_formset.prefix = "location"
        phone_number_formset.prefix = "phone"

    context = {"job_form": job_form, "experience_formset": experience_formset,
               "education_formset": education_formset, "skill_formset": skill_formset,
               "locations_formset": locations_formset, "phone_number_formset": phone_number_formset}

    return render(request, "post_a_job.html", context)


def edit_job(request, job_id):
    """EDIT THE job"""
    job = get_object_or_404(JobPost, pk=job_id)
    if request.method == 'POST':
        job_form = JobPostForm(request.POST, instance=job)
        experience_formset = ExperienceFormset(request.POST, queryset=RequiredExperience.objects.filter(job=job))
        education_formset = EducationFormset(request.POST, queryset=RequiredEducation.objects.filter(job=job))
        skill_formset = SkillFormset(request.POST, queryset=RequiredSkills.objects.filter(job=job))
        phone_number_formset = PhoneNumberFormset(request.POST, queryset=PhoneNumber.objects.filter(job=job))
        locations_formset = LocationsFormset(request.POST, queryset=Locations.objects.filter(job=job))
        experience_formset.prefix = "experience"
        education_formset.prefix = "education"
        skill_formset.prefix = "skill"
        phone_number_formset.prefix = "phone"
        locations_formset.prefix = "location"

        # The data are valid ?
        if job_form.is_valid() and experience_formset.is_valid() and education_formset.is_valid() \
                and skill_formset.is_valid() and locations_formset.is_valid() \
                and phone_number_formset.is_valid():
            new_job_form = job_form.save(commit=False)
            new_job_form.author = request.user
            new_job_form.slug = slugify(new_job_form.heading)

            for experience_form in experience_formset:
                new_experience_form = experience_form.save(commit=False)
                new_experience_form.job = new_job_form

            for education_form in education_formset:
                new_education_form = education_form.save(commit=False)
                new_education_form.job = new_job_form

            for skill_form in skill_formset:
                new_skill_form = skill_form.save(commit=False)
                new_skill_form.job = new_job_form

            for locations_form in locations_formset:
                new_locations_form = locations_form.save(commit=False)
                new_locations_form.job = new_job_form

            for phone_number_form in phone_number_formset:
                new_phone_number_form = phone_number_form.save(commit=False)
                new_phone_number_form.job = new_job_form

            new_job_form.save()
            job_form.save_m2m()

            experience_formset.save()
            education_formset.save()
            skill_formset.save()
            locations_formset.save()
            phone_number_formset.save()

            skills = RequiredSkills.objects.filter(job=new_job_form)
            experiences = RequiredExperience.objects.filter(job=new_job_form)
            educations = RequiredEducation.objects.filter(job=new_job_form)

            delete_duplicate(experiences, educations, skills)

            applies = JobApply.objects.filter(job=new_job_form)

            for apply in applies:
                apply.evaluation = compare_cv(request, apply.job_id, apply.user)
                apply.save()

            return redirect('jobs:post_list')

    else:
        job_form = JobPostForm(instance=job)

        experience_formset = ExperienceFormset(queryset=RequiredExperience.objects.filter(job=job))
        education_formset = EducationFormset(queryset=RequiredEducation.objects.filter(job=job))
        skill_formset = SkillFormset(queryset=RequiredSkills.objects.filter(job=job))
        locations_formset = LocationsFormset(queryset=Locations.objects.filter(job=job))
        phone_number_formset = PhoneNumberFormset(queryset=PhoneNumber.objects.filter(job=job))

        experience_formset.prefix = "experience"
        education_formset.prefix = "education"
        skill_formset.prefix = "skill"
        locations_formset.prefix = "location"
        phone_number_formset.prefix = "phone"

    context = {"job_form": job_form, "experience_formset": experience_formset,
               "education_formset": education_formset, "skill_formset": skill_formset,
               "locations_formset": locations_formset, "phone_number_formset": phone_number_formset}

    return render(request, "edit_job.html", context)


def delete_job(request, job_id):
    """Method to delete jobs"""
    # To get the job's id.
    job_to_delete = get_object_or_404(JobPost, pk=job_id)
    # Check if the one requesting is the job's owner.
    if request.user != job_to_delete.author:
        return HttpResponse("You don't own this job!")
    # Is it a post request ? and checks if its by the owner himself.
    if request.method == "POST" and request.user == job_to_delete.author:

jobs/templates/add_apply.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add apply</title>
</head>
<body>
    <br>
    <br>
    <br>
<form method="post" class="card shadow-lg container" style="padding: 20px; width: 50%">
{% csrf_token %}
    <p>apply info will be taken from your CV.</p>
    <br>
{{ apply_form.as_p }}
<a href="{% url 'jobs:post_list' %}" style="align-self: end"><button class=" btn btn-block btn-primary" type="submit">Apply</button></a>

</form>
</body>
</html>
{% endblock content %}

jobs/templates/delete_job.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DELETE Job</title>
</head>
<body>
    <br>
    <br>
    <br>
<form method="post">
  {% csrf_token %}
    are you sure you want to delete your post?
    <p><input type="submit" value='Yes'/>
        <a href="{{ job_to_delete.get_absolute_url }}"><input type="button" value="Cancel"></a></p>
</form>
</body>
</html>
{% endblock content %}

jobs/templates/edit_job.html
{% extends 'base.html' %}
{% block content %}
<head>
    <title>Edit job</title>
    <style>
        html, body {
      min-height: 100%;
      }
      body, div, form {
      padding: 0;
      margin: 0;
      outline: none;
      font-family: Roboto, Arial, sans-serif;
      font-size: 14px;
      line-height: 22px;
      }
      h1, h4 {
      margin: 15px 0 4px;
      }
      h1 {
      font-weight: 400;
      }

      form {
          border-radius: 50px;
      text-align: left;
      padding: 20px;
      background: #fff;
      box-shadow: 0 2px 5px #ccc;
      }
      input {
      width: calc(50% - 10px);
      padding: 5px;
      border: 1px solid #ccc;
      border-radius: 3px;
      vertical-align: middle;
      }
      input:hover {
      border: 1px solid #1c87c9;
      }
      table {
      width: 100%;
      }
      h4 {
      padding: 15px 0 5px;
      }
      .question-answer label {
      display: inline-block;
      padding: 0 20px 15px 0;
      }
      .question-answer input {
      width: auto;
      }
      textarea {
  width: 100%;
  height: 150px;
  padding: 12px 20px;
  box-sizing: border-box;
  border: 2px solid #ccc;
  border-radius: 4px;
  background-color: #f8f8f8;
  font-size: 16px;
  resize: none;
    }
      th, td {
      width: 17%;
      padding: 15px 0;
      text-align: center;
      vertical-align: unset;
      line-height: 18px;
      font-weight: 400;
      word-break: break-all;
      border-bottom: 1px solid #095484;
      color: #095484;
      }



      button {
      width: 150px;
      padding: 10px;
      border: none;
      text-align: center;
      border-radius: 5px;
      background-color: #095484;
      font-size: 16px;
      color: #fff;
      cursor: pointer;
      }
      button:hover {
      background-color: #0666a3;
      }
    label
    {
        color: darkcyan;
    }
    </style>


</head>
    <body>
        <br>
    <br>
    <br>
    <center>
       <form id="form-container" method="POST" enctype="multipart/form-data">
           {% csrf_token %}
           <h3>editing..</h3>
           {{ job_form.as_p }}
           <hr>
           <h3>Required Experiences</h3>
           {{experience_formset.management_form }}
           {% for form in experience_formset %}
           <div class="experience-form">
               {{ form.as_p }}
           </div>
           {% endfor %}
       <button id="add-experience-form" type="button">add experience</button>
       <hr>
       <h3>Required Educations</h3>
       {{ education_formset.management_form }}
       {% for form in education_formset %}
       <div class="education-form">
           {{ form.as_p }}
       </div>
       {% endfor %}
       <button id="add-education-form" type="button">add eduction</button>
       <hr>
       <h3>Required Skills</h3>
       {{ skill_formset.management_form }}
       {% for form in skill_formset %}
       <div class="skill-form">
           {{ form.as_p }}
       </div>
       {% endfor %}
       <button id="add-skill-form" type="button">add skill</button>
       <hr>
       <h3>job Locations</h3>
       {{ locations_formset.management_form }}
       {% for form in locations_formset %}
       <div class="location-form">
           {{ form.as_table}}
       </div>
       {% endfor %}
       <button id="add-location-form" type="button">add location</button>
       <hr>
       <h3>phone numbers</h3>
       {{ phone_number_formset.management_form }}
       {% for form in phone_number_formset %}
       <div class="phone-number-form">
           {{ form.as_p}}
       </div>
       {% endfor %}
       <button id="add-form" type="button">add phone number</button>
       <a href="{% url 'jobs:post_list' %}"><button type="submit">submit</button></a>
       </form>
    <br><br><br>
    <script>
            let experienceForm = document.querySelectorAll(".experience-form")
            let container = document.querySelector("#form-container")
            let experienceAddButton = document.querySelector("#add-experience-form")
            let totalExperienceForms = document.querySelector("#id_experience-TOTAL_FORMS")
            let experienceFormNum = experienceForm.length-1
            experienceAddButton.addEventListener('click', addExperienceForm)



            let educationForm = document.querySelectorAll(".education-form")
            let educationAddButton = document.querySelector("#add-education-form")
            let totalEducationForms = document.querySelector("#id_education-TOTAL_FORMS")
            let educationFormNum = educationForm.length-1
            educationAddButton.addEventListener('click', addEducationForm)

            let skillForm = document.querySelectorAll(".skill-form")
            let skillAddButton = document.querySelector("#add-skill-form")
            let totalSkillForms = document.querySelector("#id_skill-TOTAL_FORMS")
            let skillFormNum = skillForm.length-1
            skillAddButton.addEventListener('click', addSkillForm)

            let PhoneNumberForm = document.querySelectorAll(".phone-number-form")
            let PhoneNumberAddButton = document.querySelector("#add-form")
            let TotalPhoneNumberForms = document.querySelector("#id_phone-TOTAL_FORMS")
            let PhoneNumberFormNum = PhoneNumberForm.length-1
            PhoneNumberAddButton.addEventListener('click', addPhoneNumberForm)

            let locationForm = document.querySelectorAll(".location-form")
            let locationAddButton = document.querySelector("#add-location-form")
            let TotalLocationForms = document.querySelector("#id_location-TOTAL_FORMS")
            let locationFormNum = locationForm.length-1
            locationAddButton.addEventListener('click', addLocationForm)

            function addPhoneNumberForm(e){
            e.preventDefault()

            let newForm = PhoneNumberForm[0].cloneNode(true)
            let formRegex = RegExp(`phone-(\\d){1}-`,'g')

            PhoneNumberFormNum++
            newForm.innerHTML = newForm.innerHTML.replace(formRegex, `phone-${PhoneNumberFormNum}-`)
            container.insertBefore(newForm, PhoneNumberAddButton)

            TotalPhoneNumberForms.setAttribute('value', `${PhoneNumberFormNum+1}`)
        }

            function addLocationForm(e){
            e.preventDefault()

            let newForm = locationForm[0].cloneNode(true)
            let formRegex = RegExp(`location-(\\d){1}-`,'g')

            locationFormNum++
            newForm.innerHTML = newForm.innerHTML.replace(formRegex, `location-${locationFormNum}-`)
            container.insertBefore(newForm, locationAddButton)

            TotalLocationForms.setAttribute('value', `${locationFormNum+1}`)
        }

            function addSkillForm(e){
            e.preventDefault()

            let newForm = skillForm[0].cloneNode(true)
            let formRegex = RegExp(`skill-(\\d){1}-`,'g')

            skillFormNum++
            newForm.innerHTML = newForm.innerHTML.replace(formRegex, `skill-${skillFormNum}-`)
            container.insertBefore(newForm, skillAddButton)

            totalSkillForms.setAttribute('value', `${skillFormNum+1}`)
        }






            function addEducationForm(e){
            e.preventDefault()

            let newForm = educationForm[0].cloneNode(true)
            let formRegex = RegExp(`education-(\\d){1}-`,'g')

            educationFormNum++
            newForm.innerHTML = newForm.innerHTML.replace(formRegex, `education-${educationFormNum}-`)
            container.insertBefore(newForm, educationAddButton)

            totalEducationForms.setAttribute('value', `${educationFormNum+1}`)
            }


            function addExperienceForm(e){
            e.preventDefault()

            let newForm = experienceForm[0].cloneNode(true)
            let formRegex = RegExp(`experience-(\\d){1}-`,'g')

            experienceFormNum++
            newForm.innerHTML = newForm.innerHTML.replace(formRegex, `experience-${experienceFormNum}-`)
            container.insertBefore(newForm, experienceAddButton)

            totalExperienceForms.setAttribute('value', `${experienceFormNum+1}`)
        }


    </script>
    </center>
    </body>
{% endblock content %}

jobs/templates/job_post.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        button {
      width: 150px;
      padding: 10px;
      border: none;
      text-align: center;
      border-radius: 5px;
      background-color: #095484;
      font-size: 16px;
      color: #fff;
      cursor: pointer;
      }
      button:hover {
      background-color: #0666a3;
      }
        #div{
            border:4px solid black;
            margin: 40px ;
            padding: 40px;

        }
        input {
      width: calc(50% - 10px);
      padding: 5px;
      border: 1px solid #ccc;
      border-radius: 3px;
      vertical-align: middle;

      }
      input:hover {
      border: 1px solid #1c87c9;
      }

    </style>
    	<script src=
"https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js">
	</script>

	<script src=
"https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.js">
	</script>

	<link href=
"http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/ui-lightness/jquery-ui.css"
		rel="stylesheet" type="text/css" />
    <title>Job posts</title>
</head>
<body>
    <br>
    <br>
    <br>
<div class="card box shadow-lg" style="margin-left: 100px;margin-right: 100px;padding: 25px">
<center>
<p>
    <form action="{% url 'jobs:search_job' %}"  method="get" style="display:inline-table">


        <div>

         <input name="search" type="search" id="search"  placeholder="search something" style="border-radius: 2%">

            <select name="category_id" id="category_id">
            <option value="0">None</option>
                {% for category in categories%}
                    <option value="{{ category.id }}">{{ category.name }}</option>>
                {% endfor %}

            </select>
        <select name="country_id" id="country_id">
            <option value="0">None</option>
                {% for country in countries%}
                    <option value="{{ country.id }}">{{ country.country }}</option>>
                {% endfor %}

            </select>
        <button type="submit">Search</button>
         </div>
    </form>
</center>


            {% if request.user.is_authenticated %}
                <center>  <a href="{% url 'jobs:add_job' %}" ><button > Post A Job</button></a></center>

            {% endif %}

</div>
            {%for job in jobs %}
                <br>
<div class="shadow-lg card" style="margin-left: 100px;margin-right: 100px;padding: 25px;border-radius: 20px">
                      <img src="{{ job.author.photo.url }}" width="50px" height="50px" style="border-color:#1c87c9;border-radius:50%; display:inline">
                        <a href="{{ job.get_absolute_url }}" style="display: inline-block"> <h4>{{job.heading}}</h4></a>
             <sub style="text-align:right;">{{ job.created }}</sub>
    <hr style="border: 1px solid #007bff;">


    <ul style="list-style-type: none">
        <a href="{{ job.author.get_user_id }}"><li style="display: inline;margin-right: 200px">by:{{ job.author }}</li>
        </a>

        <li style="display: inline;margin-right: 200px">{{job.salary}} SP</li>

        <li style="display: inline">
                    job type:{{ job.job_type}}</li>
    </ul>

                            <hr>

            {% csrf_token %}

                </div>
            {%endfor%}
<br>
<br>
</body>
</html>
{% endblock content %}